[package]
name = "ecsdb_web"
version = "0.2.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
bytes = "1.12.1"
chrono = "0.4.45"
data-encoding = "2.11.1"
ecsdb = { path = "../ecsdb" }
form_urlencoded = "1.2.2"
futures-util = "0.3.34"
http = "1.5.0"
http-body = "1.1.0"
http-body-util = { version = "0.1.5", features = ["full"] }
humantime = "2.4.0"
iref = { version = "4.3.0", features = ["serde"] }
maud = "0.27.0"
mime = "0.3.17"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_urlencoded = "0.7.1"
thiserror = "2.0.21"
tokio = { version = "1.53.2", features = ["full"] }
tokio-util = { version = "0.7.19", features = ["futures-io", "io", "io-util"] }
tower = { version = "0.5.3", features = ["full"] }
tower-http = { version = "0.7.1", features = ["full"] }
tower-layer = "0.3.3"
tower-service = "0.3.3"
tracing = "0.1.44"
url = "2.5.8"

[dev-dependencies]
axum = "0.8.9"
hyper = { version = "1.12.0", features = ["full"] }
hyper-util = { version = "0.1.21", features = ["full"] }
tracing-subscriber = "0.3.23"
